
   name: autotranslator_example
   description: Example app for the auto_translate package.
   publish_to: 'none'

   environment:
     sdk: '>=2.17.0 <3.0.0'
     flutter: '>=3.0.0'

   dependencies:
     flutter:
       sdk: flutter
     autotranslator:
       path: ../
     provider: ^6.1.5+1
     translator: ^1.0.4+1
     connectivity_plus: ^7.0.0
     connectivity_plus_platform_interface: ^2.0.1
